### PR TITLE
Update wireguard-client-mullvad.rst verbiage

### PR DESCRIPTION
**Pull request by sburris0**
- Minor changes to improve wording
- Update since https://www.mullvad.net/en/servers/#wireguard no longer does anything
- Some clarifications

### CODE REVIEW

**Comment by sburris0** [comment]
"we assume you are familiar with the concepts of WireGuard and that
you have read the basic howto :doc:`wireguard-client`."

This part needs clarification. It sounds like the how-to expects the user to already have completed those steps but that doesn't seem right.

**Comment by Monviech** [comment]
I've read through it and the changes seem sensible. There are some merge conflicts though, could you look at them? Then we could merge it. Thanks :)

**Comment by sburris0** [comment]
Done

**Review by Monviech — APPROVED** [review]

**Comment by Monviech** [comment]
Thank you for your contribution :)

**Pull request merged**
