### PR TITLE
Zen UK IPv6 Settings

### PR DESCRIPTION
**Pull request by marjohn56**
First Revision - Someone proof read this!

I program, I hate docs... no, hold on.. I REALLY hate docs.

### CODE REVIEW

**Comment by fichtner** [comment]
Will you hate me if I ask you to use the standard theme for the pictures?

**Comment by marjohn56** [comment]
YES!


Sent from my Samsung Galaxy smartphone.
null

**Comment by fichtner** [comment]
It was worth a try. Will review the text tomorrow.

**Comment by marjohn56** [comment]
I'll redo the gfx, I'll try and do it tomorrow and the settings for sky UK.


Sent from my Samsung Galaxy smartphone.
null

**Comment by marjohn56** [comment]
Reforking.... closed

**Pull request closed without merging**
