### PR TITLE
Orange France FTTP - How to use dhclient and dhcp6

### PR DESCRIPTION
**Pull request by marjohn56**
This doc shows how to connect using our modified clients to Orange France FTTP.

### CODE REVIEW

**Comment by fabianfrz** [comment]
please downcase the file suffix

**Comment by marjohn56** [comment]
What file suffix? 
All the image files use the suffix .png

**Comment by marjohn56** [comment]
I've change the Note to use Note:: and it appears to do no formatting at all.

**Comment by fabianfrz** [comment]
you need a line break like here:
https://raw.githubusercontent.com/opnsense/docs/master/source/manual/how-tos/clamav.rst

**Comment by marjohn56** [comment]
OK, I used this guide.. obviously not that good.

https://thomas-cokelaer.info/tutorials/sphinx/rest_syntax.html#colored-boxes-note-seealso-todo-and-warnings.

I've done as you have suggested. Did René send you his files, he has sent them to me, but I saw a message where he could not find your PM.

**Comment by marjohn56** [comment]
Here's Renè's files, I cannot send you a PM either.

**Comment by fichtner** [comment]
Merged, thanks!

**Pull request merged**
