### PR TITLE
Rename FreeBSD.rst to freeBSD.rst

### PR DESCRIPTION
**Pull request by mimugmail**
make lowercase to fix the sort order, #62

### CODE REVIEW

**Comment by mimugmail** [comment]
Then also rename hardenedBSD?

https://github.com/mimugmail/docs/tree/patch-7/source/relations

**Comment by fichtner** [comment]
yes please :)

**Comment by fichtner** [comment]
@mimugmail GitHub "forgot" your changes, or was this intended?

**Comment by mimugmail** [comment]
My branch is clean, seems GH has problems as I also cannot see Rene's comments on 2FA issue in core ..

**Comment by fichtner** [comment]
merged, thanks!

**Comment by fichtner** [comment]
merged, thanks!

**Pull request merged**
