### PR TITLE
Orange France TV How To

### PR DESCRIPTION
**Pull request by marjohn56**

### CODE REVIEW

**Comment by marjohn56** [comment]
OK.. final typos corrected. Ready for pull.

**Comment by marjohn56** [comment]
Good point... I'll ask him. I know it is so he Kev needs to add that,

**Comment by marjohn56** [comment]
OK, that's added.

**Comment by fichtner** [comment]
ok, last request: please use https://pkg.opnsense.org/FreeBSD:11:amd64/snapshots/igmpproxy-0.1_2,1.txz as the other file will be cleaned up soon (MINT directory)

**Pull request merged**
