### PR TITLE
Zenarmor patch 3

### PR DESCRIPTION
**Pull request by zenarmor**
I have totally updated [zenarmor_install.rst] file according to the new Zenarmor version 1.15

### CODE REVIEW

**Comment by AdSchellevis** [comment]
@zenarmor there are some build warnings and errors in the PR, see below for examples.

```
zenarmor_install.rst:86: ERROR: Content block expected for the "Note" directive; none found.
zenarmor_install.rst:137: WARNING: Title overline too short.
```

Most are easy to fix, is this all you want to update at the moment? I can fix the errors for you, but rather do it all at once.

**Comment by zenarmor** [comment]
If you can update, I would be very happy. Yes, for now, I'm updating this
part, and I plan to work on and send the other pages on a separate branch.

**Comment by AdSchellevis** [comment]
@zenarmor ok, I'll merge and fix. please try a "make html" on your end for the next batch.

**Comment by zenarmor** [comment]
Thanks, I will.

**Comment by AdSchellevis** [comment]
https://docs.opnsense.org/vendor/sunnyvalley/zenarmor_install.html

**Pull request merged**
