### PR TITLE
bind.rst - fix spelling

### PR DESCRIPTION
**Pull request by doktornotor**
Fix spelling.

### CODE REVIEW

**Review by melroy89 — APPROVED** [review]

**Comment by doktornotor** [comment]
Well bump, the typo is still there. 😉

**Comment by fichtner** [comment]
Merged, cheers 🍻

**Comment by doktornotor** [comment]
Thanks, trying to clean up my GitHub mess.

**Comment by melroy89** [comment]
> Merged, cheers 🍻

Bedankt!

**Pull request merged**
