### PR TITLE
Update bind.rst

### PR DESCRIPTION
**Pull request by Northguy**
Added a line to alter unbound settings to make advanced settings work

### CODE REVIEW

**Comment by fichtner** [comment]
This is obsolete in 19.1 as we always bind localhost on 127.0.0.1 to avoid such issues to begin with. 😊

**Comment by Northguy** [comment]
Does this mean that the dropdownbox will disappear in 19.1? As the seting of this dropdownbox was affecting my configuration.

**Comment by fichtner** [comment]
No, drop-downs will stay there. Separate items like IP addresses or Localhost/Loopback will disappear as they are implied by the interface selected or now always on.

**Comment by Northguy** [comment]
ok. clear.

Op ma 24 dec. 2018 om 14:33 schreef Franco Fichtner <
notifications@github.com>:

**Pull request closed without merging**
