### PR TITLE
new api docs

### PR DESCRIPTION
**Pull request by mimugmail**
- wireguard
- netsnmp
- ntopng
- vnstat

### CODE REVIEW

**Comment by AdSchellevis** [comment]
@mimugmail thanks! Just out of curiosity, have you used https://github.com/fvanroie/opnsense_MakeDocs to generate these?  In the future a python script would be more practical for us to integrate in our regular toolchain, but the powershell script should deliver the correct output.

**Comment by mimugmail** [comment]
No wasn't aware of :) Just search and replace ...

**Comment by AdSchellevis** [comment]
no problem, as long as the naming is correct, we can always replace it with an automated solution in our release engineering process.

**Comment by fvanroie** [comment]
What is the best trigger for updating the docs? Should it be updated on regular intervals or with each point release?

**Comment by AdSchellevis** [comment]
we try to update when there's new content, but eventually we should look into a more solid release process (also since development and production can differ).

**Pull request merged**
