### PR TITLE
Update NAT port forward settings list

### PR DESCRIPTION
**Pull request by dpieski**
If TCP/IP version is IPv4+IPv6, the redirect target IP has to include the CIDR when using the combined. This results in 127.0.0.1/32 or ::1/128. One or the other can be put in the Target IP field.

### CODE REVIEW

**Comment by AdSchellevis** [comment]
@dpieski the set of defaults is indeed not complete, I don't agree on the note however. The target should either be IPv4 or IPv6 when using an address.

**Comment by dpieski** [comment]
Are you saying that you shouldn't use "**TCP/IP VERSION** IPv4+IPv6"?

**Comment by AdSchellevis** [comment]
yes, it probably won't pass the validations in the gui with an ipv4 or ipv6 target anyway. (if it would, pf would choose the same as the target specified, which is one family)

**Comment by dpieski** [comment]
Ah ok, so should the note advise against selecting "TCP/IP VERSION IPv4+IPv6"?

If you select IPv4+IPv6 and only enter an IPv4 address without the CIDR, it will say you have entered an invalid IPv6 address, similarly if you enter an IPv6 address without the CIDR it will say you have entered an invalid IPv4 address, however, if you add the CIDR to either the IPv4 or IPv6 address it will pass validation and work. I do not know how to tell which family pf chooses though.

**Comment by AdSchellevis** [comment]
just leave the note out and your fine :)

**Comment by dpieski** [comment]
I removed the note. 

Question for you though, for Transparent Proxy, should you have a total of 4 Rules? (1) IPv4, HTTP; (2) IPv4, HTTPS; (3) IPv6, HTTP; and (4) IPv6, HTTPS?

**Comment by AdSchellevis** [comment]
thanks! yes, you probably would.

**Pull request merged**
