### PR TITLE
www/nginx: add TLS fingerprint detection

### PR DESCRIPTION
**Pull request by fabianfrz**

### CODE REVIEW

**Comment by fichtner** [comment]
Looks ok in general, but the freehand markup in the picture should be improved...

**Comment by fabianfrz** [comment]
ok, I will try to recreate it - maybe with another tool - Maybe freehand drawing is not the right one here.

**Comment by fabianfrz** [comment]
better?

**Comment by fichtner** [comment]
Indeed, thanks! Merged.

**Pull request merged**
