### PR TITLE
Add missing options & extend or remove settings

### PR DESCRIPTION
**Pull request by melroy89**
Hi @AdSchellevis. Hier ben ik weer ;)

- Rename "Disable web GUI redirect rule" to "Http Redirect"
- Add missing "Login Messages" option
- Explain "Time zone"
- Explain "Prefer to use IPv4 even if IPv6 is available"
- Explain all "Power mode" settings

### CODE REVIEW

**Comment by AdSchellevis** [comment]
Hi @melroy89 thanks! On my end the "Server Log" setting still exists, maybe you overlooked something there?

image

**Comment by melroy89** [comment]
> Hi @melroy89 thanks! On my end the "Server Log" setting still exists, maybe you overlooked something there?
> image

Interesting... I'm running OPNsense 24.1. Then I go to: System -> Settings -> Administration.

This is what I see:

image

**Comment by melroy89** [comment]
Ps. I did restore the Server log option in this PR. Despite I'm not seeing it.

**Comment by AdSchellevis** [comment]
that is very weird, I've checked on a couple of firewalls and it's certainly there (below access log)

**Comment by melroy89** [comment]
> that is very weird, I've checked on a couple of firewalls and it's certainly there (below access log)

Also running the latest 24.1 amd64 version from your download page?

**Comment by AdSchellevis** [comment]
@melroy89 it was moved there in a minor https://github.com/opnsense/core/commit/d5b84cf46e22e03701cbda14dd93f5402d4cca42 , update to the latest and you should be fine.

**Comment by melroy89** [comment]
You're right. After updating the system, the server log option appears:

image

**Pull request merged**
