### PR TITLE
Adding Vendor Plugins > Sensei section and related documentations

### PR DESCRIPTION
**Pull request by atakane**
We've added a new section named "Vendor Plugins" under "plugins" and added "Sensei documentation" under it.

### CODE REVIEW

**Comment by AdSchellevis** [comment]
@atakane just merged your additions into a new branch https://github.com/opnsense/docs/tree/third-party

Idea is to move Third-Party plugins into their own section, which also help fitting the topics into the menu.
image

I noticed the installation instruction still uses `curl` can check with @muratbalaban43 what the new procedure will be after 19.7.2 is released?

Just create a new PR for changes on this new branch, I will merge into master later.

Can you `make clean, make html ` next time? There where quite some compile errors:
```
Running Sphinx v1.8.1
making output directory...
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 228 source files that are out of date
updating environment: 228 added, 0 changed, 0 removed
reading sources... [100%] system                                                                                                                                                                                                     
.../source/manual/how-tos/sensei_hardwarerequirements.rst:1: WARNING: Title overline too short.

=====================
Sensei: Hardware Requirements
=====================
.../source/manual/how-tos/sensei_hardwarerequirements.rst:26: WARNING: Malformed table.

+-----------------+--------------+-------------+----------------------+
| Number of Users | WAN Bandwith | Min. Memory | Min. CPU             |
+=================+==============+=============+======================+
.../source/manual/how-tos/sensei_hardwarerequirements.rst:29: WARNING: Blank line required after table.
.../source/manual/how-tos/sensei_install.rst:13: WARNING: Title underline too short.

Connect to Your Firewall
------------
.../source/manual/how-tos/sensei_install.rst:27: WARNING: Title underline too short.

Download & Run Sensei Installer
------------
.../source/manual/how-tos/sensei_install.rst:27: WARNING: Title underline too short.

Download & Run Sensei Installer
------------
.../source/manual/how-tos/sensei_install.rst:60: WARNING: Title underline too short.

Initial Configuration Wizard
------------
.../source/manual/how-tos/sensei_install.rst:60: WARNING: Title underline too short.

Initial Configuration Wizard
------------
.../source/manual/how-tos/sensei_install.rst:82: WARNING: Title overline too short.

------------
**2- Interface Selection**
------------
.../source/manual/how-tos/sensei_install.rst:82: WARNING: Title overline too short.

------------
**2- Interface Selection**
------------
.../source/manual/how-tos/sensei_install.rst:92: WARNING: Title overline too short.

------------
**3- Cloud Reputation**
------------
.../source/manual/how-tos/sensei_install.rst:92: WARNING: Title overline too short.

------------
**3- Cloud Reputation**
------------
.../source/manual/how-tos/sensei_install.rst:108: WARNING: Title overline too short.

------------
**4- Sensei CLI (Security)**
------------
.../source/manual/how-tos/sensei_install.rst:108: WARNING: Title overline too short.

------------
**4- Sensei CLI (Security)**
------------
.../source/manual/how-tos/sensei_install.rst:118: WARNING: Title overline too short.

------------
**5- Updates & Health Check**
------------
.../source/manual/how-tos/sensei_install.rst:118: WARNING: Title overline too short.

------------
**5- Updates & Health Check**
------------
.../source/manual/how-tos/sensei_install.rst:134: WARNING: Title overline too short.

------------
**6- Deployment Size**
------------
.../source/manual/how-tos/sensei_install.rst:134: WARNING: Title overline too short.

------------
**6- Deployment Size**
------------
.../source/manual/how-tos/sensei_install.rst:147: WARNING: Title overline too short.

------------
**7- Finish**
------------
.../source/manual/how-tos/sensei_install.rst:147: WARNING: Title overline too short.

------------
**7- Finish**
------------
.../source/manual/how-tos/sensei_install.rst:156: WARNING: Title overline too short.

------------
**Hands-on Video**
------------
.../source/manual/how-tos/sensei_install.rst:156: WARNING: Title overline too short.

------------
**Hands-on Video**
------------
.../source/manual/how-tos/sensei_prepareyourfirewall.rst:1: WARNING: Title overline too short.

=====================
Sensei: Prepare Your Firewall
=====================
.../source/manual/how-tos/sensei_prepareyourfirewall.rst:11: WARNING: Title overline too short.

------------
Enable Secure Shell
------------

```

**Comment by atakane** [comment]
Thanks, @AdSchellevis. Creating a new menu named "Third Party Plugins" is a much better idea than the current one and it serves to the purpose. 

I used VSCode and an internal RST extension to compile and preview the output, it seems the plugin doesn't bother to show those errors to me. I'll re-check next-time, sorry for the mess.

Also, we'll use your new branch for upcoming updates and @muratbalaban43 will address the curl issue for 19.7.2 release after he sleeps on it.

**Comment by AdSchellevis** [comment]
no problem, editors can be annoying sometimes :) 

I'll close this PR, just open a new one for changes.

**Comment by muratbalaban43** [comment]
@AdSchellevis , thanks for the review. A note how to install the plugin after 19.7.2 

Since we'll have os-sensei on OPNsense repo, it'll be enough to just issue

`pkg install os-sensei`

on the shell, and it will install. However, to be able to run this command, one still needs to enable SSH and access console. 

If you can just list the plugins in Firmware -> Plugins, that'd be awesome. 

os-sunnyvalley would be listed by default, and os-sensei would be listed if os-sunnyvalley is installed.

How does that sound?

**Comment by AdSchellevis** [comment]
@muratbalaban43 the plugin (os-sunnyvalley) should be visible as of 19.7.2 on amd64/OpenSSL, which should be Monday. (https://github.com/opnsense/tools/commit/102d3cf41db96165021025f8da9473fa41df3f5b)

**Comment by fichtner** [comment]
19.7.3

**Comment by muratbalaban43** [comment]
@AdSchellevis , thanks 👍 . For now, we can do `pkg install os-sensei` from the shell. 

Looking forward to seeing the plugin in 19.7.2.

**Comment by AdSchellevis** [comment]
@muratbalaban43 @atakane the current state is merged to master https://docs.opnsense.org/third_party_plugins.html

**Comment by muratbalaban43** [comment]
@AdSchellevis , just saw on the website. Awesome, thanks!.

**Pull request closed without merging**
