### PR TITLE
Wireguard selective routing how-to

### PR DESCRIPTION
**Pull request by Greelan**
This pull request is to add a how-to to the OPNsense documentation that describes how to implement selective routing with WireGuard with an external VPN provider. The how-to is based on this forum [tutorial](https://forum.opnsense.org/index.php?topic=21205.msg99309#msg99309).

### CODE REVIEW

**Comment by FingerlessGlov3s** [comment]
@Greelan, Looks good, mines setup the same way when I use Mullvad 👍

**Review by mimugmail — APPROVED** [review]
Nice write-up, thx 👍

**Comment by AdSchellevis** [comment]
@Greelan Thanks!

**Comment by Greelan** [comment]
> @Greelan, Looks good, mines setup the same way when I use Mullvad 👍

That's probably because much of it is based on your work (as you know)! Thanks

**Pull request merged**
