### PR TITLE
www/caddy: Add a few more details to docs

### PR DESCRIPTION
**Pull request by Monviech**
- Interface binding: https://forum.opnsense.org/index.php?topic=38714.msg200398#msg200398
- Handler logic: https://github.com/opnsense/plugins/blob/2ddbc3831d7fb5a2b3de2ad4194c0e378224f37b/www/caddy/src/opnsense/service/templates/OPNsense/Caddy/Caddyfile#L667
- Subdomain behavior with ports: https://github.com/opnsense/plugins/pull/4028
- Trouble with OPNsense WebGUI reverse proxy when it is not bound to all interfaces: https://github.com/opnsense/plugins/issues/4024#issuecomment-2148994457
- Cookie secure flag: https://github.com/opnsense/plugins/issues/4024#issuecomment-2148133814
- Syncookie and WebGUI Reverse Proxying: https://github.com/opnsense/src/issues/206
- Handler optional for HTTP-01 Challenge Redirection: https://forum.opnsense.org/index.php?topic=40357.msg200748#msg200748

### CODE REVIEW

**Comment by Monviech** [comment]
@fichtner Can this be merged for the new caddy version today?

**Comment by fichtner** [comment]
@Monviech Ad isn't around to build and push it at the moment so not really, sorry.

**Comment by AdSchellevis** [comment]
merged and published just yet, was around my machine, small effort to do this now.

**Comment by Monviech** [comment]
@AdSchellevis Thanks a lot. <3

**Pull request merged**
