### PR TITLE
Sensei Installation Documentation Updates

### PR DESCRIPTION
**Pull request by dlcasto**
Updates for the installation instructions for Sensei.

### CODE REVIEW

**Comment by dlcasto** [comment]
I'm not quite sure how to fully preview the formatting yet, but if there are any noticeable issues, please let me know! Thanks!

**Comment by AdSchellevis** [comment]
@muratbalaban43 can you review?

**Comment by muratbalaban43** [comment]
@AdSchellevis , @dlcasto thanks. 

Looks good to me.

**Comment by dlcasto** [comment]
@AdSchellevis I have updates to the Hardware Requirements page and a few miscellaneous other changes. Should I send them now as a separate pull update or wait until the Installation page is updated on OPNsense. I didn't submit all of the changes at once because the installation instructions was the highest priority and I was still working on other pages. I am finished with the other changes now which finishes up everything (unless we find any mistakes or formatting issues).

**Comment by AdSchellevis** [comment]
@dlcasto you can just add them to this pull request, I'll try to pull and test later

**Comment by dlcasto** [comment]
@AdSchellevis Thanks, I didn't realize I could add on to the request. That should be all the updates unless there are any mistakes that need corrected.

**Pull request merged**
