### PR TITLE
Fixing links only

### PR DESCRIPTION
**Pull request by linuxdude21**
Looks like that last commit my link fixes were not committed.

### CODE REVIEW

**Comment by AdSchellevis** [comment]
@linuxdude21 that was more or less intentional, these links don't appear to be functional after compiling, the full links are

**Comment by linuxdude21** [comment]
@AdSchellevis  sorry for my errors.  I think removing "#" should work, which is confusing as I see a lot of info on `<#blabla>`__ working.  Am I dealing with just reStructuredText or does Sphinx play a roll in this?

Is there any way I could compile myself to test before PRing bad syntax?

**Comment by AdSchellevis** [comment]
@linuxdude21 you certainly can, if you plan to contribute more documentation, we should indeed make sure you can validate locally to prevent us needing to compile every cycle.  The https://github.com/opnsense/docs/blob/master/README.md contains the `pip` action to install Sphinx, are you running into issues with that? and if so, which platform are you using

**Comment by linuxdude21** [comment]
@AdSchellevis Great, I will look into this tonight.  Yes I would like to do more documentation for the project.  

Did my last edits not work either?

**Comment by AdSchellevis** [comment]
@linuxdude21 I haven't tried yet, wanted to give you the opportunity to test first locally as well

**Pull request closed without merging**
