### PR TITLE
Fix some broken menu selection notations 

### PR DESCRIPTION
**Pull request by MichaelDeciso**

### CODE REVIEW

**Comment by MichaelDeciso** [comment]
I rebased the PR. I kept my change in serial_access.rst, because this is how it looks like on `master`:

afbeelding

While it looks like this in my PR:

afbeelding

**Comment by AdSchellevis** [comment]
```
source/manual/how-tos/serial_access.rst:48: WARNING: Unexpected indentation.
```

**Comment by MichaelDeciso** [comment]
Not with my branch:
```
~/Projecten/docs$ make clean
rm -rf build/*
~/Projecten/docs$ make html
sphinx-build -b html -d build/doctrees   source build/html
Running Sphinx v1.8.1
making output directory...
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 202 source files that are out of date
updating environment: 202 added, 0 changed, 0 removed
reading sources... [100%] support                                                                                                                                                                                                                                                         
looking for now-outdated files... none found
pickling environment... done
checking consistency... /Users/michael/Projecten/docs/source/manual/how-tos/ipsec-rw.rst: WARNING: document isn't included in any toctree
/Users/michael/Projecten/docs/source/manual/how-tos/ipsec-rw-android.rst: WARNING: document isn't included in any toctree
/Users/michael/Projecten/docs/source/manual/how-tos/ipsec-rw-linux.rst: WARNING: document isn't included in any toctree
/Users/michael/Projecten/docs/source/manual/how-tos/ipsec-rw-srv-eapradius.rst: WARNING: document isn't included in any toctree
/Users/michael/Projecten/docs/source/manual/how-tos/ipsec-rw-srv-eaptls.rst: WARNING: document isn't included in any toctree
/Users/michael/Projecten/docs/source/manual/how-tos/ipsec-rw-srv-ikev1xauth.rst: WARNING: document isn't included in any toctree
/Users/michael/Projecten/docs/source/manual/how-tos/ipsec-rw-srv-mschapv2.rst: WARNING: document isn't included in any toctree
/Users/michael/Projecten/docs/source/manual/how-tos/ipsec-rw-srv-rsamschapv2.rst: WARNING: document isn't included in any toctree
/Users/michael/Projecten/docs/source/manual/how-tos/ipsec-rw-w7.rst: WARNING: document isn't included in any toctree
done
preparing documents... done
writing output... [100%] support                                                                                                                                                                                                                                                          
/Users/michael/Projecten/docs/source/development/how-tos/kernel_debugging.rst:30: WARNING: Could not lex literal_block as "c". Highlighting skipped.
/Users/michael/Projecten/docs/source/manual/how-tos/ipsec-rw-srv-eapradius.rst:7: WARNING: unknown document: how-tos/ipsec-rw
/Users/michael/Projecten/docs/source/manual/how-tos/ipsec-rw-srv-eapradius.rst:42: WARNING: unknown document: how-tos/freeradius
/Users/michael/Projecten/docs/source/manual/how-tos/ipsec-rw-srv-eapradius.rst:156: WARNING: unknown document: how-tos/freeradius
/Users/michael/Projecten/docs/source/manual/how-tos/ipsec-rw-srv-ikev1xauth.rst:20: WARNING: unknown document: how-tos/ipsec-rw
/Users/michael/Projecten/docs/source/manual/how-tos/ipsec-rw-srv-mschapv2.rst:7: WARNING: unknown document: how-tos/ipsec-rw
generating indices... genindex
writing additional pages... search
copying images... [100%] manual/how-tos/images/ZenUK_image10.png                                                                                                                                                                                                                          
copying downloadable files... [100%] images/OPNsense_Logo.ai                                                                                                                                                                                                                              
copying static files... done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 15 warnings.

The HTML pages are in build/html.

Build finished. The HTML pages are in build/html.
```

**Comment by MichaelDeciso** [comment]
```
~/Projecten/docs$ git diff 31944dd01b91e619a03333b4f537ca4300b85ee4 source/manual/how-tos/serial_access.rst
diff --git a/source/manual/how-tos/serial_access.rst b/source/manual/how-tos/serial_access.rst
index ecd47d8..571cc79 100644
--- a/source/manual/how-tos/serial_access.rst
+++ b/source/manual/how-tos/serial_access.rst
@@ -43,8 +43,9 @@ The device name can differ per system and per serial device. Examples of names a
 * COM1, COM2, ... (Windows)
 
 .. Note::
-    If you have multiple devices of the same type like shown here:
+    If you have multiple devices of the same type, as shown here:
     ::
+
         ls /dev/ttyUSB*
         /dev/ttyUSB0  /dev/ttyUSB1
     
@@ -65,7 +66,7 @@ the serial console thus involves opening a terminal and executing the following
 .. Note::
     Access to the device is likely to be access restricted. You should run the command as root because running it as
     a user may lead to an access denied error on Linux / BSD.
-  
+
 If OPNsense is running, you will now be asked for your username and password if authentication is enabled. Otherwise
 the menu is displayed (at least after pressing enter). The credentials are the same as those used for SSH.
 
```

**Pull request closed without merging**
