### PR TITLE
Update wireguard-client-mullvad.rst

### PR DESCRIPTION
**Pull request by Greelan**
Include information on alternative Mullvad API to generate tunnel IPs that do not hijack DNS requests. Credit: https://schnerring.net/posts/use-custom-dns-servers-with-mullvad-and-any-wireguard-client/

### CODE REVIEW

**Comment by Greelan** [comment]
Anything more needed from me on this one @mimugmail ?

**Review by mimugmail — APPROVED** [review]
Totally fine, thx for reminder

**Comment by Greelan** [comment]
Bump :)

**Review by mimugmail — APPROVED** [review]
Fine for me :)

**Comment by fichtner** [comment]
Merged, thanks!

**Pull request merged**
